# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]

repos:
-   repo: local
    hooks:
    -   id: require-news-on-push
        name: Require bullet in NEWS.md
        description: NEWS.md must be updated with every PR.
        entry: inst/hook1
        stages: [push]
        language: r
        always_run: true
