repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: acc8657498d5bfb9e9891098ba00b36e82c7ebd6
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: 'tests/testthat/.*/.*\.R'
        additional_dependencies:
        - r-lib/styler
